//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class brk_broker
    {
        public int id { get; set; }
        public string cod_vendedor { get; set; }
        public string cod_agente_venta { get; set; }
        public string ruc { get; set; }
        public string nombre_comercial { get; set; }
        public string razon_social { get; set; }
        public string region { get; set; }
        public string email { get; set; }
        public string tipo { get; set; }
        public string texto_inicial { get; set; }
        public string email_cc_ventas { get; set; }
    }
}
