//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid CompanyID { get; set; }
        public int BrokerID { get; set; }
        public int EmpresaID { get; set; }
        public string Region { get; set; }
        public Nullable<bool> ManejaCOR { get; set; }
        public Nullable<bool> ManejaDEN { get; set; }
        public Nullable<bool> ManejaEXE { get; set; }
        public Nullable<bool> ManejaCPO { get; set; }
        public Nullable<int> FechaMaximaInclusion { get; set; }
        public Nullable<int> FechaMaximaExclusion { get; set; }
        public Nullable<int> FechaMaximaCambioCobertura { get; set; }
        public Nullable<bool> ManejaUsuarioFinal { get; set; }
        public string BrokerName { get; set; }
        public string EmpresaName { get; set; }
    }
}
