//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_GrupoNotificacion
    {
        public int IdGrupoNotificacion { get; set; }
        public string Listado { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
    }
}
