//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_ArchivoCentroCostos
    {
        public int IDArchivoCentroCostos { get; set; }
        public int IDEmpresa { get; set; }
        public string NombreArchivo { get; set; }
        public byte[] ContenidoCargado { get; set; }
        public byte[] ContenidoProcesado { get; set; }
        public string MensajeError { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string UsuarioCarga { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
