//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_FileMasivos
    {
        public int FileMasivosID { get; set; }
        public int IDEmpresa { get; set; }
        public int IDUsuario { get; set; }
        public byte[] FileContent { get; set; }
        public string Name { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public byte[] FileResult { get; set; }
        public string Observaciones { get; set; }
        public int EstadoProceso { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> PorcentajeAvance { get; set; }
    
        public virtual SEG_Usuario SEG_Usuario { get; set; }
    }
}
