//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_SolicitudPrefactura
    {
        public int IDSolicitudPrefactura { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaProcesamiento { get; set; }
        public string MensajeError { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Listas { get; set; }
    }
}
