//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_CopagoPendiente
    {
        public int CopagoPendienteID { get; set; }
        public Nullable<int> NumeroEmpresa { get; set; }
        public Nullable<int> NumeroSucursal { get; set; }
        public int NumeroContrato { get; set; }
        public string Region { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<System.DateTime> FechaBloqueo { get; set; }
        public Nullable<System.DateTime> FechaDesbloqueo { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> TipoPendiente { get; set; }
        public string NombreSucursal { get; set; }
        public string NombreTitular { get; set; }
        public string IdentificacionTitular { get; set; }
    }
}
