//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORP_NotificacionMaternidad
    {
        public int IdNotificacionMaternidad { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTitular { get; set; }
        public string NombreTitular { get; set; }
        public string IdentificacionTitular { get; set; }
        public string Tarifa { get; set; }
        public string IdLista { get; set; }
        public string AliasLista { get; set; }
        public Nullable<System.DateTime> FechaFUM { get; set; }
        public byte[] DocumentoAdjunto { get; set; }
        public Nullable<bool> EnrolamientoBebeCompleto { get; set; }
        public Nullable<System.DateTime> FechaEnrolamientoBebe { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
