//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class legacy_contrato
    {
        public string nroContrato { get; set; }
        public string nroPersona { get; set; }
        public string region { get; set; }
        public string codigoProducto { get; set; }
        public string duenioCuenta { get; set; }
        public string cedula { get; set; }
        public string codBase64 { get; set; }
        public Nullable<System.DateTime> fechaEnrolamientoCorp { get; set; }
        public Nullable<bool> EnrolamientoCorp { get; set; }
    }
}
