//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingAttachment
    {
        public long MailingAttachmentID { get; set; }
        public long MailingID { get; set; }
        public string FileName { get; set; }
        public byte[] Attachment { get; set; }
        public string ContentType { get; set; }
    
        public virtual Mailing Mailing { get; set; }
    }
}
