//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdd_websaludsaEntities : DbContext
    {
        public bdd_websaludsaEntities()
            : base("name=bdd_websaludsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<brk_broker> brk_broker { get; set; }
        public virtual DbSet<brk_usuario_broker> brk_usuario_broker { get; set; }
        public virtual DbSet<legacy_contrato> legacy_contrato { get; set; }
        public virtual DbSet<legacy_usuario> legacy_usuario { get; set; }
    }
}
