//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOT_Envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOT_Envio()
        {
            this.NOT_Destinatario = new HashSet<NOT_Destinatario>();
            this.NOT_EnvioAdjuntos = new HashSet<NOT_EnvioAdjuntos>();
        }
    
        public int IDEnvio { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<short> NumDestinatarios { get; set; }
        public Nullable<int> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOT_Destinatario> NOT_Destinatario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOT_EnvioAdjuntos> NOT_EnvioAdjuntos { get; set; }
    }
}
