//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOT_Destinatario
    {
        public int IDDestinatario { get; set; }
        public int IDEnvio { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public string Mail { get; set; }
        public Nullable<int> NumIntentos { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual NOT_Envio NOT_Envio { get; set; }
    }
}
