//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_Usuario
    {
        public int Id { get; set; }
        public int IdCorredor { get; set; }
        public string Cedula { get; set; }
        public string NombreApellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public string TelefonoFijo { get; set; }
        public string Extension { get; set; }
        public string RUCEmpresa { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int Estado { get; set; }
        public Nullable<int> TerminosCondicionesAprobado { get; set; }
        public string Region { get; set; }
        public string PermisoPlan { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<System.DateTime> fechaNacimiento2 { get; set; }
    }
}
