//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_n
    {
        public string persona_cedula { get; set; }
        public string persona_pasaporte { get; set; }
        public string persona_tipo_documento { get; set; }
        public int persona_numero { get; set; }
        public string persona_nombres { get; set; }
        public string persona_apellido_pater { get; set; }
        public string persona_apellido_mater { get; set; }
        public string persona_sexo { get; set; }
        public Nullable<System.DateTime> persona_fecha_nacimiento { get; set; }
        public string persona_estado_civil { get; set; }
        public Nullable<int> domicilio_ciudad { get; set; }
        public string domicilio_principal { get; set; }
        public string domicilio_transversal { get; set; }
        public string domiciliio_numero { get; set; }
        public string domicilio_referencia { get; set; }
        public string domicilio_latitud { get; set; }
        public string domicilio_longitud { get; set; }
        public Nullable<bool> domicilio_georeferenciada { get; set; }
        public string domicilio_email { get; set; }
        public string domicilio_telefono { get; set; }
        public string celular { get; set; }
        public string nom_emp_trabajo { get; set; }
        public string trabajo_email { get; set; }
        public string trabajo_telefono { get; set; }
        public Nullable<int> trabajo_ciudad { get; set; }
        public string trabajo_principal { get; set; }
        public string trabajo_transversal { get; set; }
        public string trabajo_numero_edificio { get; set; }
        public string trabajo_referencia { get; set; }
        public string trabajo_latitud { get; set; }
        public string trabajo_longitud { get; set; }
        public Nullable<bool> trabajo_georeferenciada { get; set; }
        public string contacto_nombres { get; set; }
        public string contacto_telefono { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string hora_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<int> persona_codigo { get; set; }
        public Nullable<int> cliente_salud { get; set; }
        public bool registro_principal { get; set; }
        public string log_cambios { get; set; }
        public string direccion_correspondencia { get; set; }
        public string operadora_celular { get; set; }
        public Nullable<System.DateTime> hora_contacto { get; set; }
        public string telefono_alterno { get; set; }
        public Nullable<int> estado_modificacion { get; set; }
        public string rango_ingresos_anual { get; set; }
        public string ocupacion { get; set; }
        public string profesion { get; set; }
        public string vehiculo { get; set; }
        public string codicion_laboral { get; set; }
        public string antiguedad_laboral { get; set; }
        public string hobby { get; set; }
        public string domicilio_barrio { get; set; }
        public string trabajo_barrio { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<bool> migrado { get; set; }
        public Nullable<int> persona_his { get; set; }
    }
}
