//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public int codigo_provincia { get; set; }
        public string nombre_provincia { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
    }
}
