//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_Siniestralidad
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdSucursalEmpresa { get; set; }
        public string Mes { get; set; }
        public string Anio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<decimal> ValorBonificado { get; set; }
        public Nullable<decimal> TotalTarifa { get; set; }
        public Nullable<decimal> Siniestralidad { get; set; }
        public Nullable<decimal> SiniestralidadIBNR { get; set; }
        public string Empresa { get; set; }
        public string Sucursal { get; set; }
        public string Ruc { get; set; }
        public Nullable<int> MesIBNR { get; set; }
        public Nullable<decimal> ValorIBNR { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public Nullable<decimal> ValorBonificadoIBNR { get; set; }
    }
}
