//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_PermisoUsuario
    {
        public int IDPermiso { get; set; }
        public int IDUsuario { get; set; }
        public int IDEmpresa { get; set; }
    
        public virtual SEG_Usuario SEG_Usuario { get; set; }
    }
}
