//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEG_Usuario()
        {
            this.CORP_FileMasivos = new HashSet<CORP_FileMasivos>();
            this.SEG_PermisoUsuario = new HashSet<SEG_PermisoUsuario>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdGrupo { get; set; }
        public string Cedula { get; set; }
        public string NombreApellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public string TelefonoFijo { get; set; }
        public string Extension { get; set; }
        public string RUCEmpresa { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int Estado { get; set; }
        public Nullable<int> TerminosCondicionesAprobado { get; set; }
        public string Region { get; set; }
        public Nullable<bool> ADUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORP_FileMasivos> CORP_FileMasivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_PermisoUsuario> SEG_PermisoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
