//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionID { get; set; }
        public string UserID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Type { get; set; }
        public int State { get; set; }
        public string Data { get; set; }
        public string Result { get; set; }
        public int ID { get; set; }
    }
}
