//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public int UserId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PersonaId { get; set; }
        public Nullable<bool> IsAuthorizator { get; set; }
        public Nullable<bool> IsSelfService { get; set; }
    }
}
