//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public string nro_cedula { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string estado_civil { get; set; }
        public string nacionalidad_ecuatoriana { get; set; }
        public string email { get; set; }
        public string direccion_calle { get; set; }
        public string direccion_calle_transversal { get; set; }
        public string direccion_numero { get; set; }
        public string direccion_piso { get; set; }
        public string direccion_depto { get; set; }
        public int id_ciudad { get; set; }
        public string telefono_1 { get; set; }
        public string telefono_2 { get; set; }
        public string telefono_3 { get; set; }
        public string trabajo_nombre { get; set; }
        public string trabajo_direccion_calle { get; set; }
        public string trabajo_direccion_calle_transversal { get; set; }
        public string trabajo_direccion_numero { get; set; }
        public Nullable<int> trabajo_id_ciudad { get; set; }
        public string trabajo_telefono_1 { get; set; }
        public string trabajo_telefono_2 { get; set; }
        public string trabajo_telefono_3 { get; set; }
        public string recibir_correspondencia { get; set; }
        public byte cambiar_password { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<byte> bloqueado { get; set; }
        public Nullable<byte> intento_login { get; set; }
        public Nullable<byte> logueado { get; set; }
        public string login { get; set; }
        public byte verificar_datos { get; set; }
        public Nullable<System.DateTime> fecha_verificacion { get; set; }
        public string datos_extra { get; set; }
        public string token_activacion { get; set; }
        public Nullable<byte> estado_activacion { get; set; }
        public string tipo_documento { get; set; }
    }
}
