//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAdmin_VTA
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdGrupo { get; set; }
        public string Cedula { get; set; }
        public string NombreApellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public string TelefonoFijo { get; set; }
        public string Extension { get; set; }
        public string RUCEmpresa { get; set; }
    }
}
