//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchLecturaArchivos.ValidacionMail {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificacionEmailChecker", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCliente.Logica.Email")]
    [System.SerializableAttribute()]
    public partial class VerificacionEmailChecker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additionalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressCheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressProvidedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressSuggestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additionalStatus {
            get {
                return this.additionalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.additionalStatusField, value) != true)) {
                    this.additionalStatusField = value;
                    this.RaisePropertyChanged("additionalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddressChecked {
            get {
                return this.emailAddressCheckedField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressCheckedField, value) != true)) {
                    this.emailAddressCheckedField = value;
                    this.RaisePropertyChanged("emailAddressChecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddressProvided {
            get {
                return this.emailAddressProvidedField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressProvidedField, value) != true)) {
                    this.emailAddressProvidedField = value;
                    this.RaisePropertyChanged("emailAddressProvided");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddressSuggestion {
            get {
                return this.emailAddressSuggestionField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressSuggestionField, value) != true)) {
                    this.emailAddressSuggestionField = value;
                    this.RaisePropertyChanged("emailAddressSuggestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificacionEmailVerifier", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCliente.Logica.Email")]
    [System.SerializableAttribute()]
    public partial class VerificacionEmailVerifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int authentication_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string limit_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limit_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int verify_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string verify_status_descField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int authentication_status {
            get {
                return this.authentication_statusField;
            }
            set {
                if ((this.authentication_statusField.Equals(value) != true)) {
                    this.authentication_statusField = value;
                    this.RaisePropertyChanged("authentication_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string limit_desc {
            get {
                return this.limit_descField;
            }
            set {
                if ((object.ReferenceEquals(this.limit_descField, value) != true)) {
                    this.limit_descField = value;
                    this.RaisePropertyChanged("limit_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit_status {
            get {
                return this.limit_statusField;
            }
            set {
                if ((this.limit_statusField.Equals(value) != true)) {
                    this.limit_statusField = value;
                    this.RaisePropertyChanged("limit_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int verify_status {
            get {
                return this.verify_statusField;
            }
            set {
                if ((this.verify_statusField.Equals(value) != true)) {
                    this.verify_statusField = value;
                    this.RaisePropertyChanged("verify_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string verify_status_desc {
            get {
                return this.verify_status_descField;
            }
            set {
                if ((object.ReferenceEquals(this.verify_status_descField, value) != true)) {
                    this.verify_status_descField = value;
                    this.RaisePropertyChanged("verify_status_desc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidacionMail.IServiciosValidacionEmail")]
    public interface IServiciosValidacionEmail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailChecker", ReplyAction="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailCheckerResponse")]
        BatchLecturaArchivos.ValidacionMail.VerificacionEmailChecker ValidarEmailChecker(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailChecker", ReplyAction="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailCheckerResponse")]
        System.Threading.Tasks.Task<BatchLecturaArchivos.ValidacionMail.VerificacionEmailChecker> ValidarEmailCheckerAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailVerifier", ReplyAction="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailVerifierResponse")]
        BatchLecturaArchivos.ValidacionMail.VerificacionEmailVerifier ValidarEmailVerifier(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailVerifier", ReplyAction="http://tempuri.org/IServiciosValidacionEmail/ValidarEmailVerifierResponse")]
        System.Threading.Tasks.Task<BatchLecturaArchivos.ValidacionMail.VerificacionEmailVerifier> ValidarEmailVerifierAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosValidacionEmailChannel : BatchLecturaArchivos.ValidacionMail.IServiciosValidacionEmail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosValidacionEmailClient : System.ServiceModel.ClientBase<BatchLecturaArchivos.ValidacionMail.IServiciosValidacionEmail>, BatchLecturaArchivos.ValidacionMail.IServiciosValidacionEmail {
        
        public ServiciosValidacionEmailClient() {
        }
        
        public ServiciosValidacionEmailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosValidacionEmailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosValidacionEmailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosValidacionEmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BatchLecturaArchivos.ValidacionMail.VerificacionEmailChecker ValidarEmailChecker(string email) {
            return base.Channel.ValidarEmailChecker(email);
        }
        
        public System.Threading.Tasks.Task<BatchLecturaArchivos.ValidacionMail.VerificacionEmailChecker> ValidarEmailCheckerAsync(string email) {
            return base.Channel.ValidarEmailCheckerAsync(email);
        }
        
        public BatchLecturaArchivos.ValidacionMail.VerificacionEmailVerifier ValidarEmailVerifier(string email) {
            return base.Channel.ValidarEmailVerifier(email);
        }
        
        public System.Threading.Tasks.Task<BatchLecturaArchivos.ValidacionMail.VerificacionEmailVerifier> ValidarEmailVerifierAsync(string email) {
            return base.Channel.ValidarEmailVerifierAsync(email);
        }
    }
}
