//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Salud.Services.ServiceSigmep {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSigmep.CheckUserSigmep")]
    public interface CheckUserSigmep {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserSigmep/CheckUserSigmep", ReplyAction="http://tempuri.org/CheckUserSigmep/CheckUserSigmepResponse")]
        int CheckUserSigmep(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckUserSigmepChannel : SW.Salud.Services.ServiceSigmep.CheckUserSigmep, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserSigmepClient : System.ServiceModel.ClientBase<SW.Salud.Services.ServiceSigmep.CheckUserSigmep>, SW.Salud.Services.ServiceSigmep.CheckUserSigmep {
        
        public CheckUserSigmepClient() {
        }
        
        public CheckUserSigmepClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckUserSigmepClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckUserSigmepClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckUserSigmepClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckUserSigmep(string login, string password) {
            return base.Channel.CheckUserSigmep(login, password);
        }
    }
}
